EF_CoreDapperTuto: EF_CoreDapperTuto.Domain.Interfaces.IApplicationWriteDbConnection Interface Reference
EF_CoreDapperTuto.Domain.Interfaces.IApplicationWriteDbConnection Interface Reference
Sets the template for the write operations on the DB (Should be at Persistance layer)
Public Member Functions
Task< int > ExecuteAsync (string sql, object param=null, IDbTransaction transaction=null, CancellationToken cancellationToken=default)
Asynchronously sends a plain string sql query through Dapper
Task< IReadOnlyList< T > > QueryAsync< T > (string sql, object param=null, IDbTransaction transaction=null, CancellationToken cancellationToken=default)
Asynchronously sends a plain string sql query through Dapper
Task< T > QueryFirstOrDefaultAsync< T > (string sql, object param=null, IDbTransaction transaction=null, CancellationToken cancellationToken=default)
Asynchronously sends a plain string sql query through Dapper, idealized to return a single record
Task< T > QuerySingleAsync< T > (string sql, object param=null, IDbTransaction transaction=null, CancellationToken cancellationToken=default)
Asynchronously sends a plain string sql query through Dapper, idealized to return a single record
Detailed Description
Sets the template for the write operations on the DB (Should be at Persistance layer)
Member Function Documentation
ExecuteAsync()
Task<int> EF_CoreDapperTuto.Domain.Interfaces.IApplicationWriteDbConnection.ExecuteAsync (string sql, object param = null, IDbTransaction transaction = null, CancellationToken cancellationToken = default)
Asynchronously sends a plain string sql query through Dapper
Parameters
sql A plain string sql query
param An object containing a parametrized query procedure
transaction Represents a transaction to be performed at a data source, and is implemented by .NET data providers that access relational databases.
cancellationToken Propagates notification that operations should be canceled.
Returns
Implemented in EF_CoreDapperTuto.Persistence.Connections.ApplicationWriteDbConnection.
QueryAsync< T >()
Task<IReadOnlyList<T> > EF_CoreDapperTuto.Domain.Interfaces.IApplicationReadDbConnection.QueryAsync< T > (string sql, object param = null, IDbTransaction transaction = null, CancellationToken cancellationToken = default) inherited
Asynchronously sends a plain string sql query through Dapper
Parameters
sql A plain string sql query
param An object containing a parametrized query procedure
transaction Represents a transaction to be performed at a data source, and is implemented by .NET data providers that access relational databases.
cancellationToken Propagates notification that operations should be canceled.
Template Parameters
T A generic type
Returns
A List of all records found by the sql query
Implemented in EF_CoreDapperTuto.Persistence.Connections.ApplicationWriteDbConnection, and EF_CoreDapperTuto.Persistence.Connections.ApplicationReadDbConnection.
References EF_CoreDapperTuto.Domain.Interfaces.IApplicationReadDbConnection.QueryFirstOrDefaultAsync< T >(), and EF_CoreDapperTuto.Domain.Interfaces.IApplicationReadDbConnection.QuerySingleAsync< T >().
QueryFirstOrDefaultAsync< T >()
Task<T> EF_CoreDapperTuto.Domain.Interfaces.IApplicationReadDbConnection.QueryFirstOrDefaultAsync< T > (string sql, object param = null, IDbTransaction transaction = null, CancellationToken cancellationToken = default) inherited
Asynchronously sends a plain string sql query through Dapper, idealized to return a single record
Parameters
sql A plain string sql query
param An object containing a parametrized query procedure
transaction Represents a transaction to be performed at a data source, and is implemented by .NET data providers that access relational databases.
cancellationToken Propagates notification that operations should be canceled.
Template Parameters
T A generic type
Returns
A single record from the DB found by the sql query
Implemented in EF_CoreDapperTuto.Persistence.Connections.ApplicationWriteDbConnection, and EF_CoreDapperTuto.Persistence.Connections.ApplicationReadDbConnection.
Referenced by EF_CoreDapperTuto.Domain.Interfaces.IApplicationReadDbConnection.QueryAsync< T >().
QuerySingleAsync< T >()
Task<T> EF_CoreDapperTuto.Domain.Interfaces.IApplicationReadDbConnection.QuerySingleAsync< T > (string sql, object param = null, IDbTransaction transaction = null, CancellationToken cancellationToken = default) inherited
Asynchronously sends a plain string sql query through Dapper, idealized to return a single record
Parameters
sql A plain string sql query
param An object containing a parametrized query procedure
transaction Represents a transaction to be performed at a data source, and is implemented by .NET data providers that access relational databases.
cancellationToken Propagates notification that operations should be canceled.
Template Parameters
T A generic type
Returns
A single record from the DB found by the sql query
Implemented in EF_CoreDapperTuto.Persistence.Connections.ApplicationWriteDbConnection, and EF_CoreDapperTuto.Persistence.Connections.ApplicationReadDbConnection.
Referenced by EF_CoreDapperTuto.Domain.Interfaces.IApplicationReadDbConnection.QueryAsync< T >().
The documentation for this interface was generated from the following file:
EF-CoreDapperTuto.Domain/Interfaces/IApplicationWriteDbConnection.cs